### PR TITLE
Removed query instance data document

### PR DESCRIPTION
**Pull request by BboyAkers**

### CODE REVIEW

**Review by jcohen-hdb — CHANGES_REQUESTED** [review]
This won't do it on it's own. I have a doc to share with you that I forgot to share with you... See Slack.

**Comment by jcohen-hdb** [comment]
I updated SUMMARY.md, so I think it's good to go now. @kriszyp Can your review? and/or want to push go?

**Review by jcohen-hdb — APPROVED** [review]
Now it should work!

**Review by kriszyp — APPROVED** [review]

**Comment by kriszyp** [comment]
But I think we want this applied to release_4.3 and release_4.4 branches too.

**Comment by BboyAkers** [comment]
@kriszyp @jcohen-hdb 
I reverted the merge. Sorry on my part ya'll 🤦🏾. Pointed a new PR to the 4.4 release branch.
https://github.com/HarperDB/documentation/pull/131

**Pull request merged**
